require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppInstancesController do

  # This should return the minimal set of attributes required to create a valid
  # AppInstance. As you add validations to AppInstance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "parent_app" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppInstancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all app_instances as @app_instances" do
      app_instance = AppInstance.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:app_instances)).to eq([app_instance])
    end
  end

  describe "GET show" do
    it "assigns the requested app_instance as @app_instance" do
      app_instance = AppInstance.create! valid_attributes
      get :show, {:id => app_instance.to_param}, valid_session
      expect(assigns(:app_instance)).to eq(app_instance)
    end
  end

  describe "GET new" do
    it "assigns a new app_instance as @app_instance" do
      get :new, {}, valid_session
      expect(assigns(:app_instance)).to be_a_new(AppInstance)
    end
  end

  describe "GET edit" do
    it "assigns the requested app_instance as @app_instance" do
      app_instance = AppInstance.create! valid_attributes
      get :edit, {:id => app_instance.to_param}, valid_session
      expect(assigns(:app_instance)).to eq(app_instance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppInstance" do
        expect {
          post :create, {:app_instance => valid_attributes}, valid_session
        }.to change(AppInstance, :count).by(1)
      end

      it "assigns a newly created app_instance as @app_instance" do
        post :create, {:app_instance => valid_attributes}, valid_session
        expect(assigns(:app_instance)).to be_a(AppInstance)
        expect(assigns(:app_instance)).to be_persisted
      end

      it "redirects to the created app_instance" do
        post :create, {:app_instance => valid_attributes}, valid_session
        expect(response).to redirect_to(AppInstance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved app_instance as @app_instance" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AppInstance).to receive(:save).and_return(false)
        post :create, {:app_instance => { "parent_app" => "invalid value" }}, valid_session
        expect(assigns(:app_instance)).to be_a_new(AppInstance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AppInstance).to receive(:save).and_return(false)
        post :create, {:app_instance => { "parent_app" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested app_instance" do
        app_instance = AppInstance.create! valid_attributes
        # Assuming there are no other app_instances in the database, this
        # specifies that the AppInstance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(AppInstance).to receive(:update).with({ "parent_app" => "" })
        put :update, {:id => app_instance.to_param, :app_instance => { "parent_app" => "" }}, valid_session
      end

      it "assigns the requested app_instance as @app_instance" do
        app_instance = AppInstance.create! valid_attributes
        put :update, {:id => app_instance.to_param, :app_instance => valid_attributes}, valid_session
        expect(assigns(:app_instance)).to eq(app_instance)
      end

      it "redirects to the app_instance" do
        app_instance = AppInstance.create! valid_attributes
        put :update, {:id => app_instance.to_param, :app_instance => valid_attributes}, valid_session
        expect(response).to redirect_to(app_instance)
      end
    end

    describe "with invalid params" do
      it "assigns the app_instance as @app_instance" do
        app_instance = AppInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AppInstance).to receive(:save).and_return(false)
        put :update, {:id => app_instance.to_param, :app_instance => { "parent_app" => "invalid value" }}, valid_session
        expect(assigns(:app_instance)).to eq(app_instance)
      end

      it "re-renders the 'edit' template" do
        app_instance = AppInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(AppInstance).to receive(:save).and_return(false)
        put :update, {:id => app_instance.to_param, :app_instance => { "parent_app" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested app_instance" do
      app_instance = AppInstance.create! valid_attributes
      expect {
        delete :destroy, {:id => app_instance.to_param}, valid_session
      }.to change(AppInstance, :count).by(-1)
    end

    it "redirects to the app_instances list" do
      app_instance = AppInstance.create! valid_attributes
      delete :destroy, {:id => app_instance.to_param}, valid_session
      expect(response).to redirect_to(app_instances_url)
    end
  end

end
